[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  command = "npm run build"
  publish = "build"

# Only apply special configuration to staging branch
[context.staging]
  command = "bash ./scripts/build-staging.sh"
  publish = "build"

[context.staging.environment]
  NODE_VERSION = "20" 