[build]
  command = "npm run build"
  publish = "build"

[context.staging]
  environment = { NODE_VERSION = "20", NODE_OPTIONS = "--openssl-legacy-provider" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 