[build]
  command = "npm run build"
  publish = "build"

[context.staging]
  command = "export CI=false && export NODE_OPTIONS='--openssl-legacy-provider' && npm run build"
  environment = { NODE_VERSION = "20" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 